home:
  - .aliases
  - .functions
  - .bash_profile
  - .condarc
  - .gitconfig
  - .p10k.zsh
  - .profile
  - .tmux.conf
  - .zprofile
  - .zshrc
  - justfile
  - .bashrc
  - .npmrc
  - .tool-versions
home_bin:
  - pycollage
links:
  - src: ssh_config
    tgt: ~/.ssh/config
    chmod: 600
  - src: zathurarc
    tgt: ~/.config/zathura/zathurarc
  - src: nvim
    tgt: ~/.config/nvim
  - src: ipython_startup/0startup.py
    tgt: ~/.ipython/profile_default/startup/0startup.py
