[project]
name = "setup-symlinks"
version = "0.1.0"
description = ""
authors = [
    {name = "Abdur Sharif",email = "rahim@shariftextiles.com"}
]
readme = "README.md"
dependencies = [
]

[tool.poetry]
packages = [{include = "setup_symlinks", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
beartype = "^0.18.2"
click = "^8.1.7"
pydantic = "^2.6.4"
python = "^3.12"
pyyaml = "^6.0.1"

[project.scripts]
setup_symlinks = "setup_symlinks.cli:cli"
