set-environment -g LC_ALL "en_IN.UTF-8"
set-environment -g LANG "en_IN.UTF-8"

set -g base-index 1
setw -g pane-base-index 1
set -g detach-on-destroy off

set -sg escape-time 0
set -g status-interval 0
set -ga terminal-overrides ",xterm:Tc"
# set -ga terminal-overrides ",xterm-256color:Tc"
set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"
set -g detach-on-destroy off
