set positional-arguments
set dotenv-load

list-recipes:
    just --list
alias default := list-recipes

get-free-port:
    #!/usr/bin/env python3
    import socket

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(('', 0))
    print(s.getsockname()[1])
