#!/usr/bin/expect

log_user 0

set timeout 300
set box [lindex $argv 0]
set app [lindex $argv 1]
set user [lindex $argv 2]

set current_year [clock format [clock seconds] -format {%Y}]
set prev_year [expr {$current_year - 1}]
set target_dir /sqpc/scratch/dse/$env(USER)/logs/$app/$box

proc run_command {cmd} {
    puts "Running: $cmd"
    send -- "$cmd && echo __OK__ || echo __FAIL__\n"
    expect {
        "__OK__" {
            puts "Ok"
        }
        "__FAIL__" {
            puts "Failed"
            # exit 1
        }
        timeout {
            puts "Timed out waiting for command output"
            exit 1
        }
        eof {
            puts "Connection closed unexpectedly"
            exit 1
        }
    }
}

spawn ssh -q -oConnectTimeout=10 -oStrictHostKeyChecking=no nyzls105i -t "sudo -u ${user} /usr/bin/sudosh"
expect $user
send "ssh -q -oConnectTimeout=10 -oStrictHostKeyChecking=no $box\n"
expect $user

send -- "stty -echo\n"
expect $user
run_command "mkdir -p ${target_dir}"
run_command "rsync \
             -a \
             --include='*/' \
             --include='${app}*.log' \
             --include='*log-${current_year}*' \
             --include='*log-${prev_year}*' \
             --exclude='*' \
            ./logs/spde/$app/ ${target_dir}"
