#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <app_name>"
    exit 1
fi

app="$1"

read -r -a HOSTS <<< "$(nomad node status -json | jq -r '.[] | .Name' | xargs)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPECT_FILE="${SCRIPT_DIR}/log_mirror_single_host"

if [ "${NOMAD_ADDR}" = "http://nyzls1517i:5646" ]; then
    user="sp_data_power_prd";
else
    user="sp_dse_prd";
fi


for host in ${HOSTS[@]}; do
	echo "${host}";
	/usr/bin/expect "${EXPECT_FILE}" "${host}" "${app}" "${user}"&
done;
wait;
